### PR TITLE
Added support for BTT SKR-2 board with TMC2130 drivers.

### PR DESCRIPTION
**Pull request by fitch22**

### CODE REVIEW

**Comment by terjeio** [comment]
Thanks for the PR.
I had to do a bit of cleanup as there were paths in the project file that were modified and caused the build to fail. I have also renamed files to match the LPC176x driver, renamed build configurations and added test for the crystal frequency HSE_VALUE to both BTT maps. A test for ganged axes has been added to the SKR 2 map as this is currently not supported when Trinamic drivers are selected.

Support for ganged axes is implemented in the LPC176x driver, either you or I can use this as a template for this? The map file has to be changed too, the code required in driver.c is already in place.

**Comment by fitch22** [comment]
Terje,
Let me see if I can make the last set of changes.  I will do another PR when I am ready.

Not sure what to do about the project paths.  I have the same problem here, can’t build until I fix the path.  Maybe I just won’t check that file back in.

Bill

**Comment by fitch22** [comment]
Terje,

I pulled all the latest changes from grblHal repository.  I see the changes you have made.

 

In btt_skr_2.0_map.h there are already definitions for M3 and M4 ports/pins/etc.  I have compared it to btt_skr_1.4_turbo_map.h and don’t see anything missing.  What other changes are needed?

 

It looks like for btt_skr_2.0.c that I need to implement the equivalent of add_cs_pin() in btt_skr_1.x.c and I would initialize hal.enumerate_pins during board_init.  Did I miss anything?

 

Bill

**Comment by terjeio** [comment]
Oops, I see the links I had in my comment were lost. Parts of Github were down for a while earlier...
[These](https://github.com/grblHAL/LPC176x/blob/f9d5b20df70eb72739642e0bca53084c439cccdf/src/btt_skr_1.3_map.h#L221-L231) are the pin definitions for the chip select lines from one of the LPC drivers, you have [these](https://github.com/grblHAL/STM32F4xx/blob/899e93d5f073676837d188a629b8298c6fbb2837/Inc/btt_skr_2.0_map.h#L190-L205). The LPC definitions are the ones I am standardizing on and they will be [picked up](https://github.com/grblHAL/STM32F4xx/blob/899e93d5f073676837d188a629b8298c6fbb2837/Src/driver.c#L250-L267) by _driver.c_ (added to the output pins array) and the [pins initialized](https://github.com/grblHAL/STM32F4xx/blob/899e93d5f073676837d188a629b8298c6fbb2837/Src/driver.c#L1576-L1588) there. You may even add the power enable pin by using a [standard definition](https://github.com/grblHAL/STM32F4xx/blob/899e93d5f073676837d188a629b8298c6fbb2837/Src/driver.c#L212-L214), note that this is not set to a known state (0 or 1) as that may differ between boards - the output should be set in the [pin enumerator](https://github.com/grblHAL/LPC176x/blob/f9d5b20df70eb72739642e0bca53084c439cccdf/src/btt_skr_1.x.c#L122).

> It looks like for btt_skr_2.0.c that I need to implement the equivalent of add_cs_pin() in btt_skr_1.x.c and I would initialize hal.enumerate_pins during board_init. 

Correct, and by letting the Trinamic plugin call the `if_init()` function it is ensured that hardware is set up and all settings loaded first. It is on my todo list to improve handling of GPIO pins routed to peripherals (SPI, UART etc.) as well but I believe some still need to be handled in the board support code. So your SPI (and later UART) initializers should stay put for now.

Adding the pins to the output pins array by using standard defines ensures consistency between board maps and drivers, possibly less code, and as a bonus the pins will be added to the `$pins` output.

**Comment by fitch22** [comment]
Terje,

Thank you so much for the detail, it really helps.  I understand.

 

Bill

**Comment by fitch22** [comment]
Terje,

I have my changes done, but have more questions☹.

 

In driver.c, there are lots of references to A, B, C and not so many for M3, M4, M5.  Are A, B, C the old way and M3, M4, M5 the new way?  Or is there some other distinction between these?  My map file now has but a single item with ABC in it, namely N_ABC_MOTORS.  Is this going away at some point?

 

Should the pins for the Trinamic SPI interface be named TRINAMIC_*?  I presently have them TMC_*.

 

In driver.c, there are checks for STEPPERS_POWER_PORT as well as TRINAMIC_MOTOR_ENABLE.  The safe power pin on the SKR-2 turns on/off the power that is fed to the stepper drivers, and they can be other driver types (like A4988) not necessarily Trinamic.  Can you explain the difference between the two?  I am assuming I should use STEPPERS_POWER_PORT for my safe power.  You indicated I should set its value in the pin enumerator.  Did you really mean if_init()?

 

There seems to be an enum missing for PinGroup_MotorChipSelect. Without that I cannot verify my code completely.

 

Thanks for your help.

 

Bill

**Comment by fitch22** [comment]
Sorry, forgot one more thing.  For some boards, you have pin modes defined as GPIO_BITBAND and others they are defined as GPIO_MAP.  I just used the same mode as the SKR PRO did since it is the same processor, but other similar processors have theirs defined as GPIO_MAP.  Can you explain how to choose?  For the SKR-2, you can set/clear bits and the processor does a read-modify-write that is safe and does not use the bit band alias.  Is one way faster than another, or have some advantage?

 

Thanks again,

Bill

**Comment by terjeio** [comment]
> In driver.c, there are lots of references to A, B, C and not so many for M3, M4, M5.  Are A, B, C the old way and M3, M4, M5 the new way?  Or is there some other distinction between these? 

M3-M5 are designations for physical motors, M3 can be mapped to A, X2, Y2 or Z2. M4 to B ,X2, Y2 or Z2. M5 to C, X2, Y2 or Z2. X2, Y2 and Z2 are designations for secondary motors - when two motors are in use for a given axis (ganged motors). Drivers supporting ganged axes may reference any mix of these.

> My map file now has but a single item with ABC in it, namely N_ABC_MOTORS.  Is this going away at some point?

No, it is the number of motors required for the configuration above the basic 3 (X,Y and Z). N_ABC_MOTORS is perhaps not the best name... Here is how N_ABC_MOTORS and related defines are set:

```
#define N_GANGED (X_GANGED + Y_GANGED + Z_GANGED)
#define N_AUTO_SQUARED (X_AUTO_SQUARE + Y_AUTO_SQUARE + Z_AUTO_SQUARE)
#define N_ABC_MOTORS (N_ABC_AXIS + N_GANGED)
```

> Should the pins for the Trinamic SPI interface be named TRINAMIC_*?  I presently have them TMC_*.

As long as these are only used in your code it does not matter.

> Can you explain the difference between the two?

`STEPPERS_POWER_PORT` is for switching on the power supply to the drivers (_VIO_),

`TRINAMIC_MOTOR_ENABLE` is for my I2C <> SPI bridge, when defined the _En_ signals are routed to the bridge microprocessor and a datagram is sent to enable/disable them. 

>  You indicated I should set its value in the pin enumerator.  Did you really mean if_init()?

No, I meant what I wrote. Add this code in the enumerator:

```
if(pin->function == Output_StepperPower)
    DIGITAL_OUT(pin->port, pin->pin, 1);
```

or add it to the switch (after removing the pin group test).

> There seems to be an enum missing for PinGroup_MotorChipSelect.

You have to pull the latest version of the core for that. It is defined in [grbl/crossbar.h](https://github.com/grblHAL/core/blob/master/crossbar.h#L256).

> For some boards, you have pin modes defined as GPIO_BITBAND and others they are defined as GPIO_MAP.

If all pins for step or direction is mapped to the same port a lookup table can be used to get the correct bits to output (including inversions). This is the fastest method to output the signals and is enabled with GPIO_MAP. Note that this cannot be used for ganged motors. GPIO_BITBAND is for updating pin output for a single pin with a write and is faster than a read-modify-write operation. I am slowly switching to using the macros DIGITAL_IN and DIGITAL_OUT in the drivers - these will use the most efficient way to update pins. Not all prococessors supports bitbanding, some has separate set and clear registers and some only supports read-modify-write. The DIGITAL_IN and DIGITAL_OUT macros will make reading and writing code simpler as they hide the way it is done. GPIO_BITBAND may be renamed later to reflect this.

I saw that you have used both HAL_GPIO_WritePin and DIGITAL_OUT in btt_skr_2.0.c. DIGITAL_OUT is the IMO best option as it does not call a function _and_ it uses bitbanding. Not terribly important in this code as it is not that time critical.

**Comment by fitch22** [comment]
Terje,

Thank you again for the helpful explanations.  I should have another PR for you soon.

 

FYI, I checked my GitHub repository and it says it is up to date with grblHal/STM32F4xx and my local one is up to date with my GitHub.  Is it possible you did not check in the new crossbar.h?

 

Thanks,

Bill

**Comment by fitch22** [comment]
Turns out crossbar.h is in grbl, and in my fork of grblHal/STM32F4xx there is just a link.  Obviously, as far as my GitHub repository is concerned, grbl is always up to date.  But when I pull or fetch to update my local repository, it seems to ignore grbl.  Any idea what the best way is to deal with this?

 

Bill

**Comment by terjeio** [comment]
> Is it possible you did not check in the new crossbar.h?

No, the [link I provided](https://github.com/grblHAL/core/blob/6f5d1cd31c06d6d27a265ccd725e61868a2a8e5b/crossbar.h#L256) is to the current version.

Did you add `--recurse-submodules` when [pulling in the update](https://github.com/grblHAL/core/wiki/Compiling-GrblHAL)?

**Comment by fitch22** [comment]
Terje,

Had to use git on the command line, and –recurse-submodules did the trick.  There is no such option in TortoiseGit which is a bummer.

 

Thank you,

Bill

**Comment by fitch22** [comment]
Terje,

I think I have fixed my issues with the last PR and I remembered that I cannot have ganged axis with Trinamic drivers.  Why is this?

 

A related question:  You explained the difference between GPIO_BITBAND and GPIO_MAP.  When an axis is ganged, step pulses need to be sent to both motors at the same time.  With the step pins of GPIO_BITBAND, it would seem there is a bit of time difference for the 2 motors.  Is this just such a small number that you don’t care, or are there ways to correct for this skew?

 

If someone were designing a CNC controller, would it be advantageous to have all the step pins be in the same port so that GPIO_MAP could be used on any combination?

 

Thanks,

Bill

**Comment by terjeio** [comment]
> I think I have fixed my issues with the last PR and I remembered that I cannot have ganged axis with Trinamic drivers.  Why is this?

You can, but not with the previous code where the Trinamic motors were adressed with `driver.axis` not  `driver.id`. It gets a bit more complicated when all drivers shares the same chip select pin and the data lines are chained. I am working on solving that now.

> When an axis is ganged, step pulses need to be sent to both motors at the same time.  With the step pins of GPIO_BITBAND, it would seem there is a bit of time difference for the 2 motors. Is this just such a small number that you don’t care, or are there ways to correct for this skew?

It is sub microsecond so I do not believe it matters, perhaps less than mechanical tolerances in most machines?
The only way to correct it is to output pulses in one go with GPIO_MAP. A larger issue is perhaps jitter due to non-constant interrupt latency?

> If someone were designing a CNC controller, would it be advantageous to have all the step pins be in the same port so that GPIO_MAP could be used on any combination?

Perhaps so, but currently GPIO_MAP cannot be used for the second motor for ganged axes - and I am not sure I will spend time on solving that in a generic way. To be sure you have to calculate the teoretical impact of the delay and check how it compares to  mechanical tolerances. Backlash, rigidity, stepper motor precision, limit switch repeatability, ...

**Pull request merged**
