### PR TITLE
Add analog output for spindle speed control to BTT SKR 2

### PR DESCRIPTION
**Pull request by fitch22**
Added analog output for spindle control with BTT_SKR_2.0.  This output works in
parallel with pwm outputs.  Board output pins rearranged slightly to accommodate
the only analog outputs on the btt_skr_2.0.

### CODE REVIEW

**Comment by terjeio** [comment]
Would it be better to add a new map file for this so that current users do not have to rewire?
The board support code can be the same if you add a #define symbol to guard the new code.

**Comment by fitch22** [comment]
That would be ok with me.  What if I use a #define in the map file as well?

if a new map file is the right approach, how would you like me to name it?

**Comment by terjeio** [comment]
>  What if I use a #define in the map file as well?

That was what I was thinking - a #define in the map file that is referenced in the board support code.

> if a new map file is the right approach, how would you like me to name it?

A suffix? Eg. _btt_skr_2.0_alt_map.h_ or _btt_skr_2.0_dac_map.h_? It should end in __map.h_.

And add something like this in _my_machine.h_?

`//#define BOARD_BTT_SKR_20_ALT      // F407 based 3D Printer board, uses analog output (DAC) for spindle RPM control`

**Comment by fitch22** [comment]
Terje,
Thanks for the reply.  I will close this PR and try again.

Bill

**Pull request closed without merging**
