### PR TITLE
Extend driver to 6 axis

### PR DESCRIPTION
**Pull request by vumario**
This PR extends STM32F4xx driver to fully support 6-axis configurations.

I also added an option to specify control signals using different PORT and PIN combinations as it was needed for my application.

Driver was tested on real hardware using STM32F407 config and everything seems to be working but there is always a chance I messed something up, so please give me your thoughts.

br,
Mario

### CODE REVIEW

**Comment by terjeio** [comment]
I am refactoring pin configuration code towards beeing able to use a crossbar for at least some pins and also for making it simpler to add pins, especially for aux I/O.

The iMXRT1062 driver already has similar code for inputs, and the MSP432E401Y driver has been just refactored for both inputs and outputs (not commited to github yet). Next out was the STM32F4xx driver as I want to use that as a start for a STM32F7xx driver. Since there are a couple of issues with this PR I decided to go ahead with the refactoring and not enter a discussion of how to make the PR mergeable. Instead I want you to help me test the refactored code if that is not too much bother for you.

Here it is:

[stm32f4refactor.zip](https://github.com/grblHAL/STM32F4xx/files/6541952/stm32f4refactor.zip)

If this is ok with you and you find issues with my code just update this PR with your suggestions. FYI it is not neeccesary to create a PR for the core changes (crossbar.h), I'll take care of that.

**Comment by vumario** [comment]
It's not a bother, I'd be happy to test the code. I am still in design stage with my project, considering controller at least, so if it works, I'm ok with it.

I'll let you know once I test this.

**Comment by vumario** [comment]
I just tried the new code and as far as I could tell, everything works, at least what I could test.

Things I tested:
 - motors, endstops and homing
 - control and probe inputs
 - mist, flood, spindle outputs
 - I2C using external EEPROM

I didn't try any SPI stuff yet because I would first need a driver for TMCs. I guess I could reuse a part of  st_morpho driver and wire the drivers in series. The board as is, is configured to use parallel SPI connection with each driver having its own CS pin on different ports. I'll see how that goes..

One thing I didn't test before is PWM output and I noticed it is not actually possible to use any pin other than PA8. It wont be a problem for me, but it would be useful to have some other options. Maybe even some kind of a generic PWM driver.

There were a few typos I found, but nothing major. Here is the modified file:

[driver.zip](https://github.com/grblHAL/STM32F4xx/files/6548252/driver.zip)

I also removed some code I believe is not used anymore.

BTW, I like the way this code looks now. It is much cleaner and it will certainly be easier to add pins if needed.
...and maybe write a parallel TMC driver.

**Comment by terjeio** [comment]
Closed as driver.c has been changed to support new style pin configurations and 6-axis support was added as part of that.

**Pull request closed without merging**
