### PR TITLE
PlatformIO: initial support for building firmware with pio

### PR DESCRIPTION
**Pull request by noahwilliamsson**
This provides four target environments:

- `nucleo_f411re_morpho_cnc` (Nucleo STM32F411 with Morpho CNC shield)
- `nucleo_f411re_protoneer` (dito buto with Protoneer CNC shield for Arduino)
- `nucleo_f446re_morpho_cnc`
- `nucleo_f446re_protoneer`

To test this out, install PlatformIO core:

- https://docs.platformio.org/en/latest/core/installation.html

Example:

    # Build all target environments
    pio run
    # Build a single target environments
    pio run -e nucleo_f411re_protoneer
    # Upload the firmware (or alternatively, copy .pio/build/<env name>/firmware.bin to the USB MSD)
    pio run -e nucleo_f411re_protoneer -t upload

I've only tested `pio run -e nucleo_f411re_protoneer` and but believe the other targets should work as well.  I haven't included all of the targets from the `.launch` files since I lack the necessary hardware to test them out.  I haven't synced the build flags that may or may not be present in the `.cproject` file created by the original IDE.

New boards can be added by duplicating an existing environment and adjusting:

- `board` (find an existing one on https://docs.platformio.org/en/latest/platforms/ststm32.html#boards and use the value from the board-specific page)
- `board_build.ldscript`
- `build_flags`
- `lib_deps`

In the future, automated build tests may be implemented using GitHub Actions --  see https://docs.platformio.org/en/latest/integration/ci/github-actions.html

### CODE REVIEW

**Comment by terjeio** [comment]
I do not understand why all the files other than platformio.ini is part of this PR. It could be me having problems understanding the github workflow or is something amiss? Do you know?

**Comment by noahwilliamsson** [comment]
@terjeio This is because my branch was behind the this project's main branch.  I fixed it with:
```
git remote add upstream git@github.com:grblHAL/STM32F4xx.git
git rebase upstream/master
git push --force
```
I've run into an issue with PlatformIO shipping a not-recent-enough version of https://github.com/STMicroelectronics/STM32CubeF4.  There's an open issue with a request to update the STM32CubeF4 version to v1.26.  I'm hoping that this will resolve an issue I'm facing where it's currently not possible to relocate the reset vector to +32KB.  I'm however not entirely sure that this will fix the problem -- there have been multiple requests to ST in their repo to allow the vector tab offset to be defined on the command line (`-D VECT_TAB_OFFSET=...`) but it seems the original request was closed with an unrelated fix and subsequent requests to fix the original problem have been closed with a redirect to the original issue (which didn't fix what was reported).  I will have to investigate this further.

I'll be busy for the next few days so it will be a while until I can work on this again.

**Comment by noahwilliamsson** [comment]
@terjeio I tried to build this today after rebasing the PR on top of your most recent changes.  Unfortunately I ran into a few compilation issues.

In https://github.com/grblHAL/Plugins_motor/commit/fe207bd10fdc2ffc29a406504c6619c9e64f1686 you introduced a `seq` parameter to `trinamic_driver_config()` along with the following code:
```
     stepper[motor.id]->get_config(motor.id)->motor.seq = seq; //
```

It seems that this new field is missing in https://github.com/terjeio/Trinamic-library/blob/master/common.h#L47-L51. Maybe you want to add something like `uint8_t seq; uint8_t _pad;` to that struct?

The build for the envs `nucleo_f411re_protoneer` and `nucleo_f446re_protoneer` also fail because:
```
...
Compiling .pio/build/nucleo_f446re_protoneer/src/serial.o
Src/driver.c:325:13: warning: 'spindle_set_speed' used but never defined
 static void spindle_set_speed (uint_fast16_t pwm_value);
             ^~~~~~~~~~~~~~~~~
Compiling .pio/build/nucleo_f446re_protoneer/src/spi.o
Src/driver.c:323:13: warning: 'pwmEnabled' defined but not used [-Wunused-variable]
 static bool pwmEnabled = false;
             ^~~~~~~~~~
Compiling .pio/build/nucleo_f446re_protoneer/src/st_morpho.o
...
Indexing .pio/build/nucleo_f446re_protoneer/libFrameworkCMSISDevice.a
Linking .pio/build/nucleo_f446re_protoneer/firmware.elf
.pio/build/nucleo_f446re_protoneer/src/driver.o: In function `spindleSetStateVariable':
driver.c:(.text.spindleSetStateVariable+0x18): undefined reference to `spindle_set_speed'
driver.c:(.text.spindleSetStateVariable+0x58): undefined reference to `spindle_set_speed'
.pio/build/nucleo_f446re_protoneer/src/driver.o: In function `driver_init':
driver.c:(.text.driver_init+0x134): undefined reference to `spindle_set_speed'
collect2: error: ld returned 1 exit status
*** [.pio/build/nucleo_f446re_protoneer/firmware.elf] Error 1
```
These builds have `-D BOARD_MORPHO_CNC=` set.  I did not investigate the cause of these issues further.

**Comment by terjeio** [comment]
> In grblHAL/Plugins_motor@fe207bd you introduced a seq parameter to trinamic_driver_config() along with the following code:

My commit script for the underlying Trinamic library was messed up, fixed now.

> The build for the envs nucleo_f411re_protoneer and nucleo_f446re_protoneer also fail because:

To be fixed in the next build/commit - the Protoneer board does not have PWM output enabled...

Are your changes ready to be merged now?

**Comment by noahwilliamsson** [comment]
> To be fixed in the next build/commit - the Protoneer board does not have PWM output enabled...
> Are your changes ready to be merged now?

I only have a Nucleo F411RE with a Protoneer board to test things out with, so I'd like to wait for the PWM fix and retest everything once more.

I'm also not sure that the `firmware.bin` files produced for the SKR Pro v1.1 and SKR 2 boards actually work (or boot) as I don't have access to this hardware.  In particular, I'm not confident that the linker script and `SCB->VTOR` is correct.

Do you have access to one of these to test with?  If not, I could break out environments in the `platformio.ini` file to a separate merge request and leave that as a draft until someone can test them out.

**Comment by terjeio** [comment]
> I only have a Nucleo F411RE with a Protoneer board to test things out with, so I'd like to wait for the PWM fix and retest everything once more.

Ok, here is the latest driver.c - can you test with that?

[driver.zip](https://github.com/grblHAL/STM32F4xx/files/7046637/driver.zip)

> I'm also not sure that the firmware.bin files produced for the SKR Pro v1.1 and SKR 2 boards actually work (or boot) as I don't have access to this hardware. In particular, I'm not confident that the linker script and SCB->VTOR is correct.

> Do you have access to one of these to test with? If not, I could break out environments in the platformio.ini file to a separate merge request and leave that as a draft until someone can test them out.

I do not have access to those boards, IMO leave the code in with a disclaimer/invitation to test rather than leave it out. It is open source after all...

**Comment by noahwilliamsson** [comment]
Thanks, it compiled fine with the updated `Src/driver.c`.  I'll try to find some time to do a quick test of the `nucleo_f411re_protoneer` target later today.

OK, no problem, I'll leave comments about it in the commit message and in the `platformio.ini` file.

Do you want me to add a quick note to the README about howto compile target ens and deploy them with PlatformIO?

**Comment by terjeio** [comment]
> Do you want me to add a quick note to the README about howto compile target ens and deploy them with PlatformIO?

Yes, please do that.

**Comment by terjeio** [comment]
> The hal.spindle.{get,update}_pwm pointers are both NULL. I assume something related to PWM changed the last week because I don't remember running into this before.

I have modified the driver for PWM timer/pin assignments to make it more flexible. Since the protoneer board does not have a PWM pin assigned and I have changed it to not assign all function pointers related to variable spindle as part of that modification the startup validation is too strict. It should be:

`driver_ok = driver_ok && (!hal.driver_cap.variable_spindle || (hal.spindle.get_pwm != NULL && hal.spindle.update_pwm != NULL));`

The core should not call variable spindle speed/PWM functions if variable spindle is not supported and I believe it does not. I have to verify this before I commit an update, nice if you can do too.

**Comment by terjeio** [comment]
I have added PWM capability to PA5, for the Protoneer board should PWM or spindle direction be the default for that pin? I would say PWM as that is the more likely usage but on the PCB the pin is marked SpnDir... What do you think?

If spindle dir adding this code makes it possible to select PWM by editing the pio file:

```
#ifdef PROTONEER_SPINDLE_PWM
#define SPINDLE_PWM_PORT_BASE   GPIOA_BASE // D13
#define SPINDLE_PWM_PIN         5
#else
#define SPINDLE_DIRECTION_PORT  GPIOA // D13
#define SPINDLE_DIRECTION_PIN   5
#endif
```

**Pull request merged**
